- name: deploy filebeat
  hosts: all
  user: root
  gather_facts: true
  vars:
  - business: "elk"
  - idc: "anchang"
  tasks:
   - name : scp filebeat rpm 
     copy : src=/opt/auto/mw_auto_plugins/package/filebeat-5.0.0-x86_64.rpm dest=/tmp/filebeat-5.0.0-x86_64.rpm
   - name : install filebeat rpm 
     yum :
        name : /tmp/filebeat-5.0.0-x86_64.rpm
        state: present
   - name: write the filebeat config file
     template: src=/opt/auto/mw_auto_plugins/scripts/filebeat/conf/filebeat_{{idc}}.j2 dest=/etc/filebeat/filebeat.yml
   - name: copy kill_logstash
     copy : src=/opt/auto/mw_auto_plugins/scripts/filebeat/conf/{{item}} dest=/root/scripts/{{item}}
     with_items:
       - "kill_logstash.sh"
   - name : kill_logstash
     shell : sh /root/scripts/kill_logstash.sh
   - name : start filebeat
     service: name=filebeat state=restarted 
