- name: deploy logstash 
  hosts: all
  user: root
  gather_facts: true
  vars:
  - business: "elk"
  - idc: "anchang"
  tasks:
   - name: Fetch Java version
     shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
     register: java_version
   - assert:
       that: 
         - java_version.stdout | version_compare('1.7', '>=') 
   - name : scp logstash rpm 
     copy : src=/opt/auto/mw_auto_plugins/package/logstash-2.3.3-1.noarch.rpm dest=/tmp/logstash-2.3.3-1.noarch.rpm 
   - name : install logstash rpm 
     yum :
        name : /tmp/logstash-2.3.3-1.noarch.rpm 
        state: present
   - name    : get domain in /var/log/nginx/
     shell   : find /var/log/nginx/ -type f -name *.access.log|awk -F'/|.access' '{print $(NF-1)}'
     register: result
   - name: write the nginx config file
     template: src=/opt/auto/mw_auto_plugins/scripts/logstash/conf/ngx_{{idc}}.j2 dest=/etc/logstash/conf.d/ngx_access.conf
   - name: copy configure
     copy : src=/opt/auto/mw_auto_plugins/scripts/logstash/conf/{{item}} dest=/etc/logstash/conf.d/{{item}}
     with_items:
       - "seaslog.conf"
       - "application.conf"
   - name : modify run user
     shell : sed -i s/LS_USER=logstash/LS_USER=root/g /etc/init.d/logstash
   - name : modify run usergroup
     shell : sed -i s/LS_GROUP=logstash/LS_GROUP=root/g /etc/init.d/logstash
   - name : start logstash
     service: name=logstash state=restarted 
